# Generated by Django 4.2.15 on 2024-08-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_psg_user_psg_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='psg_book',
        ),
        migrations.DeleteModel(
            name='psg_user',
        ),
    ]
